### ISSUE TITLE
Research integration of Google Calendar with React

### ISSUE THREAD

**Issue by lasryariel** [codefordenver/your-colorado-charity#2]

**Comment by rhynobytes** [comment]
Google Calendar integration looks possible. We need to decide how we want to pass calendar ID to the EventsService for specific subdomains

**Comment by rhynobytes** [comment]
I think the cleanest solution at the moment will be to have the EventsSerice pull from google calendar directly and combine the list of events with anything it pulls from tabletop.

Working on turning the google integration into a service where each subdomain can use a unique calendar ID, but we use a single developer API.
